### PR TITLE
Mapchangespleasepullproperly

### PR DESCRIPTION
**Pull request by Naxodile**
After many ritual sacrifices to github this should work now.

### CODE REVIEW

**Comment by Glloyd** [comment]
What map changes?

**Comment by Glloyd** [comment]
@Naxodile What were these map changes?

**Comment by Naxodile** [comment]
Every camera is now sorted by network due to the changes to camera monitoring. The research underground got the AMI RIG and was expanded. The SMESs have had their Rcon tags set properly. EVA got changed to include cooling units for FBPs and IPCs in addition there's now a medical suit cylcer and an additional medical voidsuit. Maintenance now has randomly generated loot. Medbay has two defibs in it now. And the holodeck was fixed.

**Comment by Glloyd** [comment]
If there's another medical voidsuit added, you might need to change the access to that room, because I think right now it's restricted to the CMO and the RD.

**Comment by Naxodile** [comment]
Already changed it so that either medbay or EVA access is required, also changed the windoors inside.
The inner door to actual EVA is still EVA only however.

**Comment by Glloyd** [comment]
Perfect. Keep the RD's one for him only, besides that, all's good.

**Pull request merged**
